# Generated by Django 4.2.2 on 2023-06-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_causa'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='Cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='aplicacion.cliente'),
            preserve_default=False,
        ),
    ]
