# Generated by Django 4.2.2 on 2023-06-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_presupuesto_cliente'),
        ('aplicacion', '0003_solicitud_cliente'),
    ]

    operations = [
    ]
